version: "3.0"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    command: ./script/start-server.bash
    environment:
      RAILS_ENV: test
      PUMA_PORT: 3010
    env_file:
      - .env

    volumes:
      - .:/rails

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
      - "7900:7900"
